### ISSUE TITLE
`as.data.frame()` method to obtain pixel coordinates

### ISSUE THREAD

**Issue by coolbutuseless** [trevorld/bittermelon#78]
Is there a blessed way to extract the coordinates of text?

Currently I'm doing an ugly extraction with my bespoke `bm_coords()`, but I could not see another way.

``` r
library(grid)
library(isocubes)
library(bittermelon) # on CRAN

font_file <- system.file("fonts/spleen/spleen-8x16.hex.gz", package = "bittermelon")
font <- bittermelon::read_hex(font_file)
bml <- bittermelon::as_bm_list("#RStats!", font = font)

coords <- isocubes::bm_coords(bml)
head(coords)
#>    x y idx z
#> 1 10 5   1 0
#> 2 11 5   1 0
#> 3 13 5   1 0
#> 4 14 5   1 0
#> 5 10 6   1 0
#> 6 11 6   1 0

grid.newpage()
grid.rect(coords$x * 0.3, coords$y * 0.3, width = 0.25, height = 0.25, gp = gpar(fill = 'black'), default.units = 'cm')
```

![](https://i.imgur.com/T8koOr3.png)

<sup>Created on 2024-10-26 with [reprex v2.1.1](https://reprex.tidyverse.org)</sup>

```r
# My ugly hack to get coordinates of the characters
bm_coords <- function(bml, sep = NULL) {
  
  if (length(bml) == 0) {
    return(data.frame(x = numeric(0), y = numeric(0), z = numeric(0)))
  }
  
  if (is.null(sep)) {
    sep = ncol(bml[[1]]) + 0L
  }
  
  coords <- lapply(seq_along(bml), function(i) {
    mat <- bml[[i]]
    mat <- t(mat)
    vec <- which(unclass(mat) == 1)
    coords <- arrayInd(vec, dim(mat))
    coords <- as.data.frame(coords)
    names(coords) <- c('x', 'y')
    coords$idx <- i
    coords$x <- coords$x + i * sep
    coords
  })
  
  coords <- do.call(rbind, coords)
  coords$z <- 0
  
  coords
}
```

**Comment by trevorld** [comment]
* Easiest way may be to convert the `bml` to a single bittermelon bitmap matrix and then simply use `isocubes::coords_heightmap()` on it.  
* Possibly might need to play around with `flipy` and/or `ground` arguments?  
* `bm_call(bml, cbind)` should give you an integer matrix of ones and zeros.
* i.e. `bml |> bm_call(cbind) |> coords_heatmap()`
* `{oblicubes}`'s README has an example that does something similar: https://github.com/trevorld/oblicubes?tab=readme-ov-file#bitmap-fonts

**Comment by trevorld** [comment]
After looking at the source code of `oblicubes::xyz_heightmap()` something like the following seems to work:

```
library("bittermelon")
library("dplyr")
bm <- bm_call(bml, cbind)
coords <- data.frame(
  x = rep(seq_len(ncol(bm)), each = nrow(bm)), 
  y = rep(seq_len(nrow(bm)), times = ncol(bm)),
  z = as.integer(bm)
) |> filter(z > 0) |> select(x, y)
```

**Comment by trevorld** [comment]
It looks like your `arrayInd()` approach is faster but can be simplified into fewer lines of code:

```
bm <- bm_call(bml, cbind)
coords <- arrayInd(as.logical(bm), dim(bm)) |> as.data.frame() |> stats::setNames(c("x", "y"))

# in case you need these too
coords$idx <- cut(coords$x, c(0, cumsum(bm_widths(bml, FALSE))), labels =  FALSE)
coords$z <- 0
```

**Comment by trevorld** [comment]
Fixed calc in https://github.com/trevorld/bittermelon/issues/78#issuecomment-2439678352

**Comment by trevorld** [comment]
`arrayInd()` will awkwardly let you set the column names as well although I'm not sure if that saves you any meaningful time:

```r
coords <- arrayInd(which(as.logical(bm)), dim(bm), list(y=NULL, x=NULL), TRUE) |> 
    as.data.frame()
```

**Comment by trevorld** [comment]
* Maybe always keep/add a `value` column to the data frame and just add a single `filtrate` flag to `as.data.frame()`.
*   If `filtrate` is `FALSE` return a data frame with coordinates for all values, if `filtrate` is a single integer (for `bm_bitmap` objects) or color string (for `bm_pixmap` objects) then only return the coordinates for that single `filtrate` value (using the `arrayInd()` approach).
* `filtrate` is a verb so works for `FALSE` but is also a noun for what you wanted to pass through the filter so also works for values like `1L`.  A bit rarer of a word though so maybe not the clearest flag for an ESL developer...   Couldn't find a thesaurus offering synonyms of the *noun* sense of `filtrate` so not sure if there a good high-frequency English word with similar meaning...

**Comment by trevorld** [comment]
* @coolbutuseless's use case will be `df = as.data.frame(bm, filtrate = 1L)` and will use faster `arrayInd()` approach
* By default we'll return all pixel values (slower approach)

```r
corn <- farming_crops_16x16()$corn$portrait
df <- as.data.frame(corn)
grid.circle(df$x * 0.6, df$y * 0.6, r = 0.25,
              gp = gpar(fill = df$value), default.units = 'cm')
```

![image](https://github.com/user-attachments/assets/ec656e74-b04f-4177-878e-92c19da5aa06)
